name: diox_flutter_transformer
description:  A DioX transformer for flutter, by which the json decoding will be in background with [compute] function in flutter sdk.

version: 1.0.0
homepage: https://github.com/arklabsnz/diox_flutter_transformer

environment:
  sdk: ">2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  diox: ^5.0.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: